# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtWidgets


class UiMainWindow(object):
    def __init__(self):
        super().__init__()

    def setup_ui(self, window):
        window.setObjectName("MainWindow")
        window.setMinimumSize(1, 1)
        self.centralwidget = QtWidgets.QWidget(window)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(4, 4, -1, 4)
        self.formLayout.setObjectName("formLayout")
        self.line_output = QtWidgets.QLineEdit(self.centralwidget)
        self.line_output.setObjectName("line_output")
        self.line_output.setReadOnly(True)
        self.formLayout.setWidget(
            0, QtWidgets.QFormLayout.SpanningRole, self.line_output
        )
        self.lbl_height = QtWidgets.QLabel(self.centralwidget)
        self.lbl_height.setObjectName("lbl_height")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbl_height)
        self.lbl_weight = QtWidgets.QLabel(self.centralwidget)
        self.lbl_weight.setObjectName("lbl_weight")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lbl_weight)
        self.spin_height = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.spin_height.setDecimals(1)
        self.spin_height.setObjectName("spin_height")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spin_height)
        self.spin_weight = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.spin_weight.setObjectName("spin_weight")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spin_weight)
        self.verticalLayout.addLayout(self.formLayout)
        window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 341, 21))
        self.menubar.setObjectName("menubar")
        window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(window)
        self.statusbar.setObjectName("statusbar")
        window.setStatusBar(self.statusbar)

        self.retranslate_ui(window)
        QtCore.QMetaObject.connectSlotsByName(window)

    def retranslate_ui(self, window):
        _translate = QtCore.QCoreApplication.translate
        window.setWindowTitle(_translate("MainWindow", "BMI Calculator"))
        self.lbl_height.setText(_translate("MainWindow", "height (cm)"))
        self.lbl_weight.setText(_translate("MainWindow", "weight (kg)"))

    def set_bounds(self, spin_control, lower_limit, upper_limit):
        spin_control.setMinimum(lower_limit)
        spin_control.setMaximum(upper_limit)
